USE [master]
GO

/****** Object:  Database [SoftUni]    Script Date: 30.11.2022 г. 0:09:55 ******/
CREATE DATABASE [SoftUni]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SoftUni', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SoftUni.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SoftUni_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SoftUni_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SoftUni].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SoftUni] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SoftUni] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SoftUni] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SoftUni] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SoftUni] SET ARITHABORT OFF 
GO

ALTER DATABASE [SoftUni] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [SoftUni] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SoftUni] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SoftUni] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SoftUni] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SoftUni] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SoftUni] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SoftUni] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SoftUni] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SoftUni] SET  ENABLE_BROKER 
GO

ALTER DATABASE [SoftUni] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SoftUni] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SoftUni] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SoftUni] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SoftUni] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SoftUni] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SoftUni] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SoftUni] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SoftUni] SET  MULTI_USER 
GO

ALTER DATABASE [SoftUni] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SoftUni] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SoftUni] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SoftUni] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SoftUni] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SoftUni] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SoftUni] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SoftUni] SET  READ_WRITE 
GO

