USE [master]
GO

/****** Object:  Database [University]    Script Date: 28.11.2022 г. 23:23:26 ******/
CREATE DATABASE [University]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'University', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\University.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'University_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\University_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [University].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [University] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [University] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [University] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [University] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [University] SET ARITHABORT OFF 
GO

ALTER DATABASE [University] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [University] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [University] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [University] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [University] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [University] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [University] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [University] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [University] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [University] SET  ENABLE_BROKER 
GO

ALTER DATABASE [University] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [University] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [University] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [University] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [University] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [University] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [University] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [University] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [University] SET  MULTI_USER 
GO

ALTER DATABASE [University] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [University] SET DB_CHAINING OFF 
GO

ALTER DATABASE [University] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [University] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [University] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [University] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [University] SET QUERY_STORE = OFF
GO

ALTER DATABASE [University] SET  READ_WRITE 
GO

