CREATE TABLE Clients ( 
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL 
)

CREATE TABLE AccountTypes ( 
	Id INT PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL 
)

CREATE TABLE Accounts ( Id INT PRIMARY KEY IDENTITY,
	AccountTypeId INT FOREIGN KEY REFERENCES AccountTypes(Id),
	Balance DECIMAL(15, 2) NOT NULL DEFAULT(0),
	ClientId INT FOREIGN KEY REFERENCES Clients(Id) 
)

CREATE TABLE Transactions ( 
	Id INT PRIMARY KEY IDENTITY,
	AccountId INT FOREIGN KEY REFERENCES Accounts(Id),
	OldBalance DECIMAL(15, 2) NOT NULL,
	NewBalance DECIMAL(15, 2) NOT NULL, Amount AS NewBalance - OldBalance,
	[DateTime] DATETIME2 
	)